sensor:
    - platform: mqtt
      name: 'cistern_level'
      state_topic: 'borgo/cistern/level'
      unit_of_measurement: '%'
      value_template: "{{ value | round(1) }}"

    - platform: mqtt
      name: 'cistern_dist'
      state_topic: 'borgo/cistern/dist'
      unit_of_measurement: 'cm'
      value_template: "{{ value | round(1) }}"

    - platform: mqtt
      name: 'cistern_health'
      state_topic: 'borgo/cistern/health'
      unit_of_measurement: '%'